In [4]:
import torch
import torch.nn as nn

In [5]:
centers = nn.Parameter(torch.randn(10,2))

In [6]:
centers

Parameter containing:
tensor([[ 0.2570, -0.7191],
        [ 2.4151, -0.7098],
        [ 0.4448, -0.2066],
        [-2.3802,  0.0403],
        [ 1.3209,  1.9965],
        [ 1.3893, -1.3802],
        [ 0.2508, -0.8091],
        [-0.4990, -0.1926],
        [-0.5403,  0.4584],
        [ 1.3463, -1.1519]], requires_grad=True)

In [7]:
centers.shape

torch.Size([10, 2])

In [8]:
centers[0]

tensor([ 0.2570, -0.7191], grad_fn=<SelectBackward>)

In [9]:
x = nn.Parameter(torch.randn(4,2))

In [10]:
x

Parameter containing:
tensor([[-0.4783, -1.6346],
        [ 0.4219,  0.1733],
        [ 0.4491,  0.0172],
        [ 0.8206,  0.3095]], requires_grad=True)

In [11]:
torch.pow(x,2)

tensor([[2.2877e-01, 2.6718e+00],
        [1.7796e-01, 3.0017e-02],
        [2.0168e-01, 2.9729e-04],
        [6.7333e-01, 9.5767e-02]], grad_fn=<PowBackward0>)

In [12]:
torch.pow(x,2).sum(dim=1, keepdim=True)

tensor([[2.9006],
        [0.2080],
        [0.2020],
        [0.7691]], grad_fn=<SumBackward1>)

In [13]:
torch.pow(x,2).sum(dim=1, keepdim=True).expand(4,2)

tensor([[2.9006, 2.9006],
        [0.2080, 0.2080],
        [0.2020, 0.2020],
        [0.7691, 0.7691]], grad_fn=<ExpandBackward>)